application:
   security: 
      jwt:
         secretKey: 763979244226452948404D6351655468576D5A7134743777217A25432A462D4A
         validityInMs: 3600000   # an hour
         refresh-token: 
            validityInMs: 604800000   # 7 days
         confirm-token: 
            validityInMs: 900000   # 15 minutes
frontend:
  base-url: http://localhost:3000
backend:
  base-url: http://localhost:8080
server:
   port: 8080
spring:
   config:
      activate:
         on-profile: default
      import: env.properties
   data:
      mongodb:
         host: localhost
         port: 27017
         database: artconnect-db
         auto-index-creation: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: artbymurz@gmail.com
      password: ${GMAIL_PASSWORD}
      properties.mail.smtp:
         auth: true
         starttls.enable: true
---
application:
   security: 
      jwt:
         secretKey: 763979244226452948404D6351655468576D5A7134743777217A25432A462D4A
         validityInMs: 3600000   # an hour
         refresh-token: 
            validityInMs: 604800000   # 7 days
         confirm-token: 
            validityInMs: 900000   # 15 minutes
frontend:
  base-url: http://18.185.79.47:3000
backend:
  base-url: http://18.185.79.47:8080
spring:
   config:
      activate:
         on-profile: docker
      import: env.properties
   data:
      mongodb:
         url: mongodb+srv://artconnect:AauS5wGE27kAFocz@artconnetc-cluster.hh5a4oh.mongodb.net/?retryWrites=true&w=majority
         database: artconnect-db
         auto-index-creation: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: artbymurz@gmail.com
      password: ${GMAIL_PASSWORD}
      properties.mail.smtp:
         auth: true
         starttls.enable: true