name: Build and push Docker image

on:
  create:
    tags:
      - 'v*' # Trigger on tags matching v*, e.g., v1.0, v2.3.4

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set backend image name
        run: echo "ARTCONNECT_BACKEND_IMAGE=ghcr.io/smurzz/artconnect-backend:${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Set frontend image name
        run: echo "ARTCONNECT_FRONTEND_IMAGE=ghcr.io/smurzz/artconnect-frontend:${{ github.event.ref }}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push artconnect-backend image
        uses: docker/build-push-action@v2
        with:
          context: ac-backend
          push: true
          tags: ${{ env.ARTCONNECT_BACKEND_IMAGE }}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Build and push artconnect-frontend image
        uses: docker/build-push-action@v2
        with:
          context: ac-frontend
          push: true
          tags: ${{ env.ARTCONNECT_FRONTEND_IMAGE }}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
