name: Build and push Docker image

on:
   push:
      branches:
      - [*]
      tags:
      - '*'

jobs:
   build-and-push:
      runs-on: ubuntu-latest
      steps:
      -  name: Checkout code
         uses: actions/checkout@v2

      -  name: Log in to GitHub Container Registry
         uses: docker/login-action@v1
         with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      -  name: Build and push artconnect-backend image
         uses: docker/build-push-action@v2
         with:
            context: ac-backend
            push: true
            tags: ghcr.io/smurzz/artconnect-backend:1.0.0
         env:
            CR_PAT: ${{ secrets.CR_PAT }}

      -  name: Build and push artconnect-frontend image
         uses: docker/build-push-action@v2
         with:
            context: ac-frontend
            push: true
            tags: ghcr.io/smurzz/artconnect-frontend:1.0.0
         env:
            CR_PAT: ${{ secrets.CR_PAT }}